//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBayAIR.eBayTF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ebay.com/marketplace/services", ConfigurationName="eBayTF.FileTransferServicePort")]
    public interface FileTransferServicePort {
        
        // CODEGEN: Generating message contract since the operation uploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:uploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
        eBayAIR.eBayTF.uploadFileResponse1 uploadFile(eBayAIR.eBayTF.uploadFileRequest1 request);
        
        // CODEGEN: Generating message contract since the operation downloadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:downloadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
        eBayAIR.eBayTF.downloadFileResponse1 downloadFile(eBayAIR.eBayTF.downloadFileRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class UploadFileRequest : BaseServiceRequest {
        
        private string taskReferenceIdField;
        
        private string fileReferenceIdField;
        
        private string fileFormatField;
        
        private FileAttachment fileAttachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskReferenceId {
            get {
                return this.taskReferenceIdField;
            }
            set {
                this.taskReferenceIdField = value;
                this.RaisePropertyChanged("taskReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fileReferenceId {
            get {
                return this.fileReferenceIdField;
            }
            set {
                this.fileReferenceIdField = value;
                this.RaisePropertyChanged("fileReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
        public string fileFormat {
            get {
                return this.fileFormatField;
            }
            set {
                this.fileFormatField = value;
                this.RaisePropertyChanged("fileFormat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FileAttachment fileAttachment {
            get {
                return this.fileAttachmentField;
            }
            set {
                this.fileAttachmentField = value;
                this.RaisePropertyChanged("fileAttachment");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class FileAttachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long sizeField;
        
        private bool sizeFieldSpecified;
        
        private byte[] dataField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class ErrorParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class ErrorData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long errorIdField;
        
        private string domainField;
        
        private ErrorSeverity severityField;
        
        private ErrorCategory categoryField;
        
        private string messageField;
        
        private string subdomainField;
        
        private string exceptionIdField;
        
        private ErrorParameter[] parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
                this.RaisePropertyChanged("errorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
                this.RaisePropertyChanged("domain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ErrorSeverity severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ErrorCategory category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subdomain {
            get {
                return this.subdomainField;
            }
            set {
                this.subdomainField = value;
                this.RaisePropertyChanged("subdomain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=6)]
        public string exceptionId {
            get {
                return this.exceptionIdField;
            }
            set {
                this.exceptionIdField = value;
                this.RaisePropertyChanged("exceptionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter", IsNullable=true, Order=7)]
        public ErrorParameter[] parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("parameter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public enum ErrorSeverity {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public enum ErrorCategory {
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Application,
        
        /// <remarks/>
        Request,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DownloadFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UploadFileResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public abstract partial class BaseServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AckValue ackField;
        
        private ErrorData[] errorMessageField;
        
        private string versionField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AckValue ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
                this.RaisePropertyChanged("ack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("error")]
        public ErrorData[] errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public enum AckValue {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        PartialFailure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class DownloadFileResponse : BaseServiceResponse {
        
        private FileAttachment fileAttachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FileAttachment fileAttachment {
            get {
                return this.fileAttachmentField;
            }
            set {
                this.fileAttachmentField = value;
                this.RaisePropertyChanged("fileAttachment");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class UploadFileResponse : BaseServiceResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DownloadFileRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UploadFileRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public abstract partial class BaseServiceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
    public partial class DownloadFileRequest : BaseServiceRequest {
        
        private string taskReferenceIdField;
        
        private string fileReferenceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskReferenceId {
            get {
                return this.taskReferenceIdField;
            }
            set {
                this.taskReferenceIdField = value;
                this.RaisePropertyChanged("taskReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fileReferenceId {
            get {
                return this.fileReferenceIdField;
            }
            set {
                this.fileReferenceIdField = value;
                this.RaisePropertyChanged("fileReferenceId");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eBayAIR.eBayTF.UploadFileRequest uploadFileRequest;
        
        public uploadFileRequest1() {
        }
        
        public uploadFileRequest1(eBayAIR.eBayTF.UploadFileRequest uploadFileRequest) {
            this.uploadFileRequest = uploadFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eBayAIR.eBayTF.UploadFileResponse uploadFileResponse;
        
        public uploadFileResponse1() {
        }
        
        public uploadFileResponse1(eBayAIR.eBayTF.UploadFileResponse uploadFileResponse) {
            this.uploadFileResponse = uploadFileResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eBayAIR.eBayTF.DownloadFileRequest downloadFileRequest;
        
        public downloadFileRequest1() {
        }
        
        public downloadFileRequest1(eBayAIR.eBayTF.DownloadFileRequest downloadFileRequest) {
            this.downloadFileRequest = downloadFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class downloadFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eBayAIR.eBayTF.DownloadFileResponse downloadFileResponse;
        
        public downloadFileResponse1() {
        }
        
        public downloadFileResponse1(eBayAIR.eBayTF.DownloadFileResponse downloadFileResponse) {
            this.downloadFileResponse = downloadFileResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileTransferServicePortChannel : eBayAIR.eBayTF.FileTransferServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransferServicePortClient : System.ServiceModel.ClientBase<eBayAIR.eBayTF.FileTransferServicePort>, eBayAIR.eBayTF.FileTransferServicePort {
        
        public FileTransferServicePortClient() {
        }
        
        public FileTransferServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransferServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBayAIR.eBayTF.uploadFileResponse1 eBayAIR.eBayTF.FileTransferServicePort.uploadFile(eBayAIR.eBayTF.uploadFileRequest1 request) {
            return base.Channel.uploadFile(request);
        }
        
        public eBayAIR.eBayTF.UploadFileResponse uploadFile(eBayAIR.eBayTF.UploadFileRequest uploadFileRequest) {
            eBayAIR.eBayTF.uploadFileRequest1 inValue = new eBayAIR.eBayTF.uploadFileRequest1();
            inValue.uploadFileRequest = uploadFileRequest;
            eBayAIR.eBayTF.uploadFileResponse1 retVal = ((eBayAIR.eBayTF.FileTransferServicePort)(this)).uploadFile(inValue);
            return retVal.uploadFileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBayAIR.eBayTF.downloadFileResponse1 eBayAIR.eBayTF.FileTransferServicePort.downloadFile(eBayAIR.eBayTF.downloadFileRequest1 request) {
            return base.Channel.downloadFile(request);
        }
        
        public eBayAIR.eBayTF.DownloadFileResponse downloadFile(eBayAIR.eBayTF.DownloadFileRequest downloadFileRequest) {
            eBayAIR.eBayTF.downloadFileRequest1 inValue = new eBayAIR.eBayTF.downloadFileRequest1();
            inValue.downloadFileRequest = downloadFileRequest;
            eBayAIR.eBayTF.downloadFileResponse1 retVal = ((eBayAIR.eBayTF.FileTransferServicePort)(this)).downloadFile(inValue);
            return retVal.downloadFileResponse;
        }
    }
}
