//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ebay.com/marketplace/services", ConfigurationName="BulkDataExchangeServicePort")]
public interface BulkDataExchangeServicePort
{
    
    // CODEGEN: Generating message contract since the operation createUploadJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:createUploadJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    createUploadJobResponse1 createUploadJob(createUploadJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation startUploadJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:startUploadJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    startUploadJobResponse1 startUploadJob(startUploadJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation abortJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:abortJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    abortJobResponse1 abortJob(abortJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getJobs is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getJobs", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    getJobsResponse1 getJobs(getJobsRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getJobStatus is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getJobStatus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    getJobStatusResponse1 getJobStatus(getJobStatusRequest1 request);
    
    // CODEGEN: Generating message contract since the operation startDownloadJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:startDownloadJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    startDownloadJobResponse1 startDownloadJob(startDownloadJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation createRecurringJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:createRecurringJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    createRecurringJobResponse1 createRecurringJob(createRecurringJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation deleteRecurringJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:deleteRecurringJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    deleteRecurringJobResponse1 deleteRecurringJob(deleteRecurringJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getRecurringJobs is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getRecurringJobs", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    getRecurringJobsResponse1 getRecurringJobs(getRecurringJobsRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getRecurringJobExecutionStatus is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getRecurringJobExecutionStatus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    getRecurringJobExecutionStatusResponse1 getRecurringJobExecutionStatus(getRecurringJobExecutionStatusRequest1 request);
    
    // CODEGEN: Generating message contract since the operation getRecurringJobExecutionHistory is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getRecurringJobExecutionHistory", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    getRecurringJobExecutionHistoryResponse1 getRecurringJobExecutionHistory(getRecurringJobExecutionHistoryRequest1 request);
    
    // CODEGEN: Generating message contract since the operation activateRecurringJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:activateRecurringJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    activateRecurringJobResponse1 activateRecurringJob(activateRecurringJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation suspendRecurringJob is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:suspendRecurringJob", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    suspendRecurringJobResponse1 suspendRecurringJob(suspendRecurringJobRequest1 request);
    
    // CODEGEN: Generating message contract since the operation abortRecurringJobExecution is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:abortRecurringJobExecution", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseServiceRequest))]
    abortRecurringJobExecutionResponse1 abortRecurringJobExecution(abortRecurringJobExecutionRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class CreateUploadJobRequest : BaseServiceRequest
{
    
    private string uploadJobTypeField;
    
    private string uUIDField;
    
    private FileType fileTypeField;
    
    private bool fileTypeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string uploadJobType
    {
        get
        {
            return this.uploadJobTypeField;
        }
        set
        {
            this.uploadJobTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string UUID
    {
        get
        {
            return this.uUIDField;
        }
        set
        {
            this.uUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public FileType fileType
    {
        get
        {
            return this.fileTypeField;
        }
        set
        {
            this.fileTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fileTypeSpecified
    {
        get
        {
            return this.fileTypeFieldSpecified;
        }
        set
        {
            this.fileTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public enum FileType
{
    
    /// <remarks/>
    XML,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AbortRecurringJobExecutionRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SuspendRecurringJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivateRecurringJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRecurringJobExecutionHistoryRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRecurringJobExecutionStatusRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRecurringJobsRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRecurringJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateRecurringJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartDownloadJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetJobStatusRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetJobsRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AbortJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartUploadJobRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateUploadJobRequest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public abstract partial class BaseServiceRequest
{
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class RecurringJobDetail
{
    
    private string recurringJobIdField;
    
    private System.DateTime creationTimeField;
    
    private int frequencyInMinutesField;
    
    private string downloadJobTypeField;
    
    private RecurringJobStatus jobStatusField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime creationTime
    {
        get
        {
            return this.creationTimeField;
        }
        set
        {
            this.creationTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int frequencyInMinutes
    {
        get
        {
            return this.frequencyInMinutesField;
        }
        set
        {
            this.frequencyInMinutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=3)]
    public string downloadJobType
    {
        get
        {
            return this.downloadJobTypeField;
        }
        set
        {
            this.downloadJobTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public RecurringJobStatus jobStatus
    {
        get
        {
            return this.jobStatusField;
        }
        set
        {
            this.jobStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public enum RecurringJobStatus
{
    
    /// <remarks/>
    Active,
    
    /// <remarks/>
    Suspended,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class JobProfile
{
    
    private string jobIdField;
    
    private string jobTypeField;
    
    private JobStatus jobStatusField;
    
    private System.DateTime creationTimeField;
    
    private System.DateTime completionTimeField;
    
    private bool completionTimeFieldSpecified;
    
    private int errorCountField;
    
    private bool errorCountFieldSpecified;
    
    private double percentCompleteField;
    
    private bool percentCompleteFieldSpecified;
    
    private string fileReferenceIdField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string jobId
    {
        get
        {
            return this.jobIdField;
        }
        set
        {
            this.jobIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=1)]
    public string jobType
    {
        get
        {
            return this.jobTypeField;
        }
        set
        {
            this.jobTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public JobStatus jobStatus
    {
        get
        {
            return this.jobStatusField;
        }
        set
        {
            this.jobStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime creationTime
    {
        get
        {
            return this.creationTimeField;
        }
        set
        {
            this.creationTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime completionTime
    {
        get
        {
            return this.completionTimeField;
        }
        set
        {
            this.completionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool completionTimeSpecified
    {
        get
        {
            return this.completionTimeFieldSpecified;
        }
        set
        {
            this.completionTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int errorCount
    {
        get
        {
            return this.errorCountField;
        }
        set
        {
            this.errorCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool errorCountSpecified
    {
        get
        {
            return this.errorCountFieldSpecified;
        }
        set
        {
            this.errorCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public double percentComplete
    {
        get
        {
            return this.percentCompleteField;
        }
        set
        {
            this.percentCompleteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool percentCompleteSpecified
    {
        get
        {
            return this.percentCompleteFieldSpecified;
        }
        set
        {
            this.percentCompleteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string fileReferenceId
    {
        get
        {
            return this.fileReferenceIdField;
        }
        set
        {
            this.fileReferenceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=8)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public enum JobStatus
{
    
    /// <remarks/>
    Created,
    
    /// <remarks/>
    Scheduled,
    
    /// <remarks/>
    InProcess,
    
    /// <remarks/>
    Completed,
    
    /// <remarks/>
    Aborted,
    
    /// <remarks/>
    Failed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class ErrorParameter
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class ErrorData
{
    
    private long errorIdField;
    
    private string domainField;
    
    private ErrorSeverity severityField;
    
    private ErrorCategory categoryField;
    
    private string messageField;
    
    private string subdomainField;
    
    private string exceptionIdField;
    
    private ErrorParameter[] parameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public long errorId
    {
        get
        {
            return this.errorIdField;
        }
        set
        {
            this.errorIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string domain
    {
        get
        {
            return this.domainField;
        }
        set
        {
            this.domainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public ErrorSeverity severity
    {
        get
        {
            return this.severityField;
        }
        set
        {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public ErrorCategory category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string subdomain
    {
        get
        {
            return this.subdomainField;
        }
        set
        {
            this.subdomainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=6)]
    public string exceptionId
    {
        get
        {
            return this.exceptionIdField;
        }
        set
        {
            this.exceptionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter", IsNullable=true, Order=7)]
    public ErrorParameter[] parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public enum ErrorSeverity
{
    
    /// <remarks/>
    Error,
    
    /// <remarks/>
    Warning,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public enum ErrorCategory
{
    
    /// <remarks/>
    System,
    
    /// <remarks/>
    Application,
    
    /// <remarks/>
    Request,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AbortRecurringJobExecutionResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SuspendRecurringJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivateRecurringJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRecurringJobExecutionHistoryResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRecurringJobExecutionStatusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRecurringJobsResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRecurringJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateRecurringJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartDownloadJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetJobStatusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GetJobsResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AbortJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(StartUploadJobResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateUploadJobResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public abstract partial class BaseServiceResponse
{
    
    private AckValue ackField;
    
    private ErrorData[] errorMessageField;
    
    private string versionField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    //private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public AckValue ack
    {
        get
        {
            return this.ackField;
        }
        set
        {
            this.ackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("error")]
    public ErrorData[] errorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timestampSpecified
    {
        get
        {
            return this.timestampFieldSpecified;
        }
        set
        {
            this.timestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    //[System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
    //public System.Xml.XmlElement[] Any
    //{
    //    get
    //    {
    //        return this.anyField;
    //    }
    //    set
    //    {
    //        this.anyField = value;
    //    }
    //}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public enum AckValue
{
    
    /// <remarks/>
    Success,
    
    /// <remarks/>
    Failure,
    
    /// <remarks/>
    Warning,
    
    /// <remarks/>
    PartialFailure,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class AbortRecurringJobExecutionResponse : BaseServiceResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class SuspendRecurringJobResponse : BaseServiceResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class ActivateRecurringJobResponse : BaseServiceResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetRecurringJobExecutionHistoryResponse : BaseServiceResponse
{
    
    private JobProfile[] jobProfileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobProfile", Order=0)]
    public JobProfile[] jobProfile
    {
        get
        {
            return this.jobProfileField;
        }
        set
        {
            this.jobProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetRecurringJobExecutionStatusResponse : BaseServiceResponse
{
    
    private JobProfile jobProfileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public JobProfile jobProfile
    {
        get
        {
            return this.jobProfileField;
        }
        set
        {
            this.jobProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetRecurringJobsResponse : BaseServiceResponse
{
    
    private RecurringJobDetail[] recurringJobDetailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("recurringJobDetail", Order=0)]
    public RecurringJobDetail[] recurringJobDetail
    {
        get
        {
            return this.recurringJobDetailField;
        }
        set
        {
            this.recurringJobDetailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class DeleteRecurringJobResponse : BaseServiceResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class CreateRecurringJobResponse : BaseServiceResponse
{
    
    private string recurringJobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class StartDownloadJobResponse : BaseServiceResponse
{
    
    private string jobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string jobId
    {
        get
        {
            return this.jobIdField;
        }
        set
        {
            this.jobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetJobStatusResponse : BaseServiceResponse
{
    
    private JobProfile[] jobProfileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobProfile", Order=0)]
    public JobProfile[] jobProfile
    {
        get
        {
            return this.jobProfileField;
        }
        set
        {
            this.jobProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetJobsResponse : BaseServiceResponse
{
    
    private JobProfile[] jobProfileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobProfile", Order=0)]
    public JobProfile[] jobProfile
    {
        get
        {
            return this.jobProfileField;
        }
        set
        {
            this.jobProfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class AbortJobResponse : BaseServiceResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class StartUploadJobResponse : BaseServiceResponse
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class CreateUploadJobResponse : BaseServiceResponse
{
    
    private string jobIdField;
    
    private string fileReferenceIdField;
    
    private string maxFileSizeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string jobId
    {
        get
        {
            return this.jobIdField;
        }
        set
        {
            this.jobIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string fileReferenceId
    {
        get
        {
            return this.fileReferenceIdField;
        }
        set
        {
            this.fileReferenceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string maxFileSize
    {
        get
        {
            return this.maxFileSizeField;
        }
        set
        {
            this.maxFileSizeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class FeeSettlementReportFilter
{
    
    private System.DateTime startTimeField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime startTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class DownloadRequestFilter
{
    
    private FeeSettlementReportFilter feeSettlementReportFilterField;
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public FeeSettlementReportFilter feeSettlementReportFilter
    {
        get
        {
            return this.feeSettlementReportFilterField;
        }
        set
        {
            this.feeSettlementReportFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
    public System.Xml.XmlElement[] Any
    {
        get
        {
            return this.anyField;
        }
        set
        {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class AbortRecurringJobExecutionRequest : BaseServiceRequest
{
    
    private string recurringJobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class SuspendRecurringJobRequest : BaseServiceRequest
{
    
    private string recurringJobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class ActivateRecurringJobRequest : BaseServiceRequest
{
    
    private string recurringJobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetRecurringJobExecutionHistoryRequest : BaseServiceRequest
{
    
    private System.DateTime startTimeField;
    
    private bool startTimeFieldSpecified;
    
    private System.DateTime endTimeField;
    
    private bool endTimeFieldSpecified;
    
    private string recurringJobIdField;
    
    private JobStatus[] jobStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime startTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startTimeSpecified
    {
        get
        {
            return this.startTimeFieldSpecified;
        }
        set
        {
            this.startTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime endTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endTimeSpecified
    {
        get
        {
            return this.endTimeFieldSpecified;
        }
        set
        {
            this.endTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobStatus", Order=3)]
    public JobStatus[] jobStatus
    {
        get
        {
            return this.jobStatusField;
        }
        set
        {
            this.jobStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetRecurringJobExecutionStatusRequest : BaseServiceRequest
{
    
    private string recurringJobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetRecurringJobsRequest : BaseServiceRequest
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class DeleteRecurringJobRequest : BaseServiceRequest
{
    
    private string recurringJobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string recurringJobId
    {
        get
        {
            return this.recurringJobIdField;
        }
        set
        {
            this.recurringJobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class CreateRecurringJobRequest : BaseServiceRequest
{
    
    private string uUIDField;
    
    private int frequencyInMinutesField;
    
    private string downloadJobTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string UUID
    {
        get
        {
            return this.uUIDField;
        }
        set
        {
            this.uUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public int frequencyInMinutes
    {
        get
        {
            return this.frequencyInMinutesField;
        }
        set
        {
            this.frequencyInMinutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=2)]
    public string downloadJobType
    {
        get
        {
            return this.downloadJobTypeField;
        }
        set
        {
            this.downloadJobTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class StartDownloadJobRequest : BaseServiceRequest
{
    
    private string downloadJobTypeField;
    
    private string uUIDField;
    
    private DownloadRequestFilter downloadRequestFilterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
    public string downloadJobType
    {
        get
        {
            return this.downloadJobTypeField;
        }
        set
        {
            this.downloadJobTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string UUID
    {
        get
        {
            return this.uUIDField;
        }
        set
        {
            this.uUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DownloadRequestFilter downloadRequestFilter
    {
        get
        {
            return this.downloadRequestFilterField;
        }
        set
        {
            this.downloadRequestFilterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetJobStatusRequest : BaseServiceRequest
{
    
    private string jobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string jobId
    {
        get
        {
            return this.jobIdField;
        }
        set
        {
            this.jobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class GetJobsRequest : BaseServiceRequest
{
    
    private System.DateTime creationTimeFromField;
    
    private bool creationTimeFromFieldSpecified;
    
    private System.DateTime creationTimeToField;
    
    private bool creationTimeToFieldSpecified;
    
    private string[] jobTypeField;
    
    private JobStatus[] jobStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime creationTimeFrom
    {
        get
        {
            return this.creationTimeFromField;
        }
        set
        {
            this.creationTimeFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationTimeFromSpecified
    {
        get
        {
            return this.creationTimeFromFieldSpecified;
        }
        set
        {
            this.creationTimeFromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime creationTimeTo
    {
        get
        {
            return this.creationTimeToField;
        }
        set
        {
            this.creationTimeToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationTimeToSpecified
    {
        get
        {
            return this.creationTimeToFieldSpecified;
        }
        set
        {
            this.creationTimeToFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobType", DataType="token", Order=2)]
    public string[] jobType
    {
        get
        {
            return this.jobTypeField;
        }
        set
        {
            this.jobTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("jobStatus", Order=3)]
    public JobStatus[] jobStatus
    {
        get
        {
            return this.jobStatusField;
        }
        set
        {
            this.jobStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class AbortJobRequest : BaseServiceRequest
{
    
    private string jobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string jobId
    {
        get
        {
            return this.jobIdField;
        }
        set
        {
            this.jobIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebay.com/marketplace/services")]
public partial class StartUploadJobRequest : BaseServiceRequest
{
    
    private string jobIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string jobId
    {
        get
        {
            return this.jobIdField;
        }
        set
        {
            this.jobIdField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class createUploadJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CreateUploadJobRequest createUploadJobRequest;
    
    public createUploadJobRequest1()
    {
    }
    
    public createUploadJobRequest1(CreateUploadJobRequest createUploadJobRequest)
    {
        this.createUploadJobRequest = createUploadJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class createUploadJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CreateUploadJobResponse createUploadJobResponse;
    
    public createUploadJobResponse1()
    {
    }
    
    public createUploadJobResponse1(CreateUploadJobResponse createUploadJobResponse)
    {
        this.createUploadJobResponse = createUploadJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class startUploadJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public StartUploadJobRequest startUploadJobRequest;
    
    public startUploadJobRequest1()
    {
    }
    
    public startUploadJobRequest1(StartUploadJobRequest startUploadJobRequest)
    {
        this.startUploadJobRequest = startUploadJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class startUploadJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public StartUploadJobResponse startUploadJobResponse;
    
    public startUploadJobResponse1()
    {
    }
    
    public startUploadJobResponse1(StartUploadJobResponse startUploadJobResponse)
    {
        this.startUploadJobResponse = startUploadJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class abortJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AbortJobRequest abortJobRequest;
    
    public abortJobRequest1()
    {
    }
    
    public abortJobRequest1(AbortJobRequest abortJobRequest)
    {
        this.abortJobRequest = abortJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class abortJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AbortJobResponse abortJobResponse;
    
    public abortJobResponse1()
    {
    }
    
    public abortJobResponse1(AbortJobResponse abortJobResponse)
    {
        this.abortJobResponse = abortJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getJobsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetJobsRequest getJobsRequest;
    
    public getJobsRequest1()
    {
    }
    
    public getJobsRequest1(GetJobsRequest getJobsRequest)
    {
        this.getJobsRequest = getJobsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getJobsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetJobsResponse getJobsResponse;
    
    public getJobsResponse1()
    {
    }
    
    public getJobsResponse1(GetJobsResponse getJobsResponse)
    {
        this.getJobsResponse = getJobsResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getJobStatusRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetJobStatusRequest getJobStatusRequest;
    
    public getJobStatusRequest1()
    {
    }
    
    public getJobStatusRequest1(GetJobStatusRequest getJobStatusRequest)
    {
        this.getJobStatusRequest = getJobStatusRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getJobStatusResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetJobStatusResponse getJobStatusResponse;
    
    public getJobStatusResponse1()
    {
    }
    
    public getJobStatusResponse1(GetJobStatusResponse getJobStatusResponse)
    {
        this.getJobStatusResponse = getJobStatusResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class startDownloadJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public StartDownloadJobRequest startDownloadJobRequest;
    
    public startDownloadJobRequest1()
    {
    }
    
    public startDownloadJobRequest1(StartDownloadJobRequest startDownloadJobRequest)
    {
        this.startDownloadJobRequest = startDownloadJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class startDownloadJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public StartDownloadJobResponse startDownloadJobResponse;
    
    public startDownloadJobResponse1()
    {
    }
    
    public startDownloadJobResponse1(StartDownloadJobResponse startDownloadJobResponse)
    {
        this.startDownloadJobResponse = startDownloadJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class createRecurringJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CreateRecurringJobRequest createRecurringJobRequest;
    
    public createRecurringJobRequest1()
    {
    }
    
    public createRecurringJobRequest1(CreateRecurringJobRequest createRecurringJobRequest)
    {
        this.createRecurringJobRequest = createRecurringJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class createRecurringJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CreateRecurringJobResponse createRecurringJobResponse;
    
    public createRecurringJobResponse1()
    {
    }
    
    public createRecurringJobResponse1(CreateRecurringJobResponse createRecurringJobResponse)
    {
        this.createRecurringJobResponse = createRecurringJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class deleteRecurringJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DeleteRecurringJobRequest deleteRecurringJobRequest;
    
    public deleteRecurringJobRequest1()
    {
    }
    
    public deleteRecurringJobRequest1(DeleteRecurringJobRequest deleteRecurringJobRequest)
    {
        this.deleteRecurringJobRequest = deleteRecurringJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class deleteRecurringJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DeleteRecurringJobResponse deleteRecurringJobResponse;
    
    public deleteRecurringJobResponse1()
    {
    }
    
    public deleteRecurringJobResponse1(DeleteRecurringJobResponse deleteRecurringJobResponse)
    {
        this.deleteRecurringJobResponse = deleteRecurringJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getRecurringJobsRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetRecurringJobsRequest getRecurringJobsRequest;
    
    public getRecurringJobsRequest1()
    {
    }
    
    public getRecurringJobsRequest1(GetRecurringJobsRequest getRecurringJobsRequest)
    {
        this.getRecurringJobsRequest = getRecurringJobsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getRecurringJobsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetRecurringJobsResponse getRecurringJobsResponse;
    
    public getRecurringJobsResponse1()
    {
    }
    
    public getRecurringJobsResponse1(GetRecurringJobsResponse getRecurringJobsResponse)
    {
        this.getRecurringJobsResponse = getRecurringJobsResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getRecurringJobExecutionStatusRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetRecurringJobExecutionStatusRequest getRecurringJobExecutionStatusRequest;
    
    public getRecurringJobExecutionStatusRequest1()
    {
    }
    
    public getRecurringJobExecutionStatusRequest1(GetRecurringJobExecutionStatusRequest getRecurringJobExecutionStatusRequest)
    {
        this.getRecurringJobExecutionStatusRequest = getRecurringJobExecutionStatusRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getRecurringJobExecutionStatusResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetRecurringJobExecutionStatusResponse getRecurringJobExecutionStatusResponse;
    
    public getRecurringJobExecutionStatusResponse1()
    {
    }
    
    public getRecurringJobExecutionStatusResponse1(GetRecurringJobExecutionStatusResponse getRecurringJobExecutionStatusResponse)
    {
        this.getRecurringJobExecutionStatusResponse = getRecurringJobExecutionStatusResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getRecurringJobExecutionHistoryRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetRecurringJobExecutionHistoryRequest getRecurringJobExecutionHistoryRequest;
    
    public getRecurringJobExecutionHistoryRequest1()
    {
    }
    
    public getRecurringJobExecutionHistoryRequest1(GetRecurringJobExecutionHistoryRequest getRecurringJobExecutionHistoryRequest)
    {
        this.getRecurringJobExecutionHistoryRequest = getRecurringJobExecutionHistoryRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getRecurringJobExecutionHistoryResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public GetRecurringJobExecutionHistoryResponse getRecurringJobExecutionHistoryResponse;
    
    public getRecurringJobExecutionHistoryResponse1()
    {
    }
    
    public getRecurringJobExecutionHistoryResponse1(GetRecurringJobExecutionHistoryResponse getRecurringJobExecutionHistoryResponse)
    {
        this.getRecurringJobExecutionHistoryResponse = getRecurringJobExecutionHistoryResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class activateRecurringJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ActivateRecurringJobRequest activateRecurringJobRequest;
    
    public activateRecurringJobRequest1()
    {
    }
    
    public activateRecurringJobRequest1(ActivateRecurringJobRequest activateRecurringJobRequest)
    {
        this.activateRecurringJobRequest = activateRecurringJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class activateRecurringJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ActivateRecurringJobResponse activateRecurringJobResponse;
    
    public activateRecurringJobResponse1()
    {
    }
    
    public activateRecurringJobResponse1(ActivateRecurringJobResponse activateRecurringJobResponse)
    {
        this.activateRecurringJobResponse = activateRecurringJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class suspendRecurringJobRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SuspendRecurringJobRequest suspendRecurringJobRequest;
    
    public suspendRecurringJobRequest1()
    {
    }
    
    public suspendRecurringJobRequest1(SuspendRecurringJobRequest suspendRecurringJobRequest)
    {
        this.suspendRecurringJobRequest = suspendRecurringJobRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class suspendRecurringJobResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SuspendRecurringJobResponse suspendRecurringJobResponse;
    
    public suspendRecurringJobResponse1()
    {
    }
    
    public suspendRecurringJobResponse1(SuspendRecurringJobResponse suspendRecurringJobResponse)
    {
        this.suspendRecurringJobResponse = suspendRecurringJobResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class abortRecurringJobExecutionRequest1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AbortRecurringJobExecutionRequest abortRecurringJobExecutionRequest;
    
    public abortRecurringJobExecutionRequest1()
    {
    }
    
    public abortRecurringJobExecutionRequest1(AbortRecurringJobExecutionRequest abortRecurringJobExecutionRequest)
    {
        this.abortRecurringJobExecutionRequest = abortRecurringJobExecutionRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class abortRecurringJobExecutionResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ebay.com/marketplace/services", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public AbortRecurringJobExecutionResponse abortRecurringJobExecutionResponse;
    
    public abortRecurringJobExecutionResponse1()
    {
    }
    
    public abortRecurringJobExecutionResponse1(AbortRecurringJobExecutionResponse abortRecurringJobExecutionResponse)
    {
        this.abortRecurringJobExecutionResponse = abortRecurringJobExecutionResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface BulkDataExchangeServicePortChannel : BulkDataExchangeServicePort, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BulkDataExchangeServicePortClient : System.ServiceModel.ClientBase<BulkDataExchangeServicePort>, BulkDataExchangeServicePort
{
    
    public BulkDataExchangeServicePortClient()
    {
    }
    
    public BulkDataExchangeServicePortClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BulkDataExchangeServicePortClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BulkDataExchangeServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BulkDataExchangeServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    createUploadJobResponse1 BulkDataExchangeServicePort.createUploadJob(createUploadJobRequest1 request)
    {
        return base.Channel.createUploadJob(request);
    }
    
    public CreateUploadJobResponse createUploadJob(CreateUploadJobRequest createUploadJobRequest)
    {
        createUploadJobRequest1 inValue = new createUploadJobRequest1();
        inValue.createUploadJobRequest = createUploadJobRequest;
        createUploadJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).createUploadJob(inValue);
        return retVal.createUploadJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    startUploadJobResponse1 BulkDataExchangeServicePort.startUploadJob(startUploadJobRequest1 request)
    {
        return base.Channel.startUploadJob(request);
    }
    
    public StartUploadJobResponse startUploadJob(StartUploadJobRequest startUploadJobRequest)
    {
        startUploadJobRequest1 inValue = new startUploadJobRequest1();
        inValue.startUploadJobRequest = startUploadJobRequest;
        startUploadJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).startUploadJob(inValue);
        return retVal.startUploadJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    abortJobResponse1 BulkDataExchangeServicePort.abortJob(abortJobRequest1 request)
    {
        return base.Channel.abortJob(request);
    }
    
    public AbortJobResponse abortJob(AbortJobRequest abortJobRequest)
    {
        abortJobRequest1 inValue = new abortJobRequest1();
        inValue.abortJobRequest = abortJobRequest;
        abortJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).abortJob(inValue);
        return retVal.abortJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getJobsResponse1 BulkDataExchangeServicePort.getJobs(getJobsRequest1 request)
    {
        return base.Channel.getJobs(request);
    }
    
    public GetJobsResponse getJobs(GetJobsRequest getJobsRequest)
    {
        getJobsRequest1 inValue = new getJobsRequest1();
        inValue.getJobsRequest = getJobsRequest;
        getJobsResponse1 retVal = ((BulkDataExchangeServicePort)(this)).getJobs(inValue);
        return retVal.getJobsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getJobStatusResponse1 BulkDataExchangeServicePort.getJobStatus(getJobStatusRequest1 request)
    {
        return base.Channel.getJobStatus(request);
    }
    
    public GetJobStatusResponse getJobStatus(GetJobStatusRequest getJobStatusRequest)
    {
        getJobStatusRequest1 inValue = new getJobStatusRequest1();
        inValue.getJobStatusRequest = getJobStatusRequest;
        getJobStatusResponse1 retVal = ((BulkDataExchangeServicePort)(this)).getJobStatus(inValue);
        return retVal.getJobStatusResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    startDownloadJobResponse1 BulkDataExchangeServicePort.startDownloadJob(startDownloadJobRequest1 request)
    {
        return base.Channel.startDownloadJob(request);
    }
    
    public StartDownloadJobResponse startDownloadJob(StartDownloadJobRequest startDownloadJobRequest)
    {
        startDownloadJobRequest1 inValue = new startDownloadJobRequest1();
        inValue.startDownloadJobRequest = startDownloadJobRequest;
        startDownloadJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).startDownloadJob(inValue);
        return retVal.startDownloadJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    createRecurringJobResponse1 BulkDataExchangeServicePort.createRecurringJob(createRecurringJobRequest1 request)
    {
        return base.Channel.createRecurringJob(request);
    }
    
    public CreateRecurringJobResponse createRecurringJob(CreateRecurringJobRequest createRecurringJobRequest)
    {
        createRecurringJobRequest1 inValue = new createRecurringJobRequest1();
        inValue.createRecurringJobRequest = createRecurringJobRequest;
        createRecurringJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).createRecurringJob(inValue);
        return retVal.createRecurringJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    deleteRecurringJobResponse1 BulkDataExchangeServicePort.deleteRecurringJob(deleteRecurringJobRequest1 request)
    {
        return base.Channel.deleteRecurringJob(request);
    }
    
    public DeleteRecurringJobResponse deleteRecurringJob(DeleteRecurringJobRequest deleteRecurringJobRequest)
    {
        deleteRecurringJobRequest1 inValue = new deleteRecurringJobRequest1();
        inValue.deleteRecurringJobRequest = deleteRecurringJobRequest;
        deleteRecurringJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).deleteRecurringJob(inValue);
        return retVal.deleteRecurringJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getRecurringJobsResponse1 BulkDataExchangeServicePort.getRecurringJobs(getRecurringJobsRequest1 request)
    {
        return base.Channel.getRecurringJobs(request);
    }
    
    public GetRecurringJobsResponse getRecurringJobs(GetRecurringJobsRequest getRecurringJobsRequest)
    {
        getRecurringJobsRequest1 inValue = new getRecurringJobsRequest1();
        inValue.getRecurringJobsRequest = getRecurringJobsRequest;
        getRecurringJobsResponse1 retVal = ((BulkDataExchangeServicePort)(this)).getRecurringJobs(inValue);
        return retVal.getRecurringJobsResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getRecurringJobExecutionStatusResponse1 BulkDataExchangeServicePort.getRecurringJobExecutionStatus(getRecurringJobExecutionStatusRequest1 request)
    {
        return base.Channel.getRecurringJobExecutionStatus(request);
    }
    
    public GetRecurringJobExecutionStatusResponse getRecurringJobExecutionStatus(GetRecurringJobExecutionStatusRequest getRecurringJobExecutionStatusRequest)
    {
        getRecurringJobExecutionStatusRequest1 inValue = new getRecurringJobExecutionStatusRequest1();
        inValue.getRecurringJobExecutionStatusRequest = getRecurringJobExecutionStatusRequest;
        getRecurringJobExecutionStatusResponse1 retVal = ((BulkDataExchangeServicePort)(this)).getRecurringJobExecutionStatus(inValue);
        return retVal.getRecurringJobExecutionStatusResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getRecurringJobExecutionHistoryResponse1 BulkDataExchangeServicePort.getRecurringJobExecutionHistory(getRecurringJobExecutionHistoryRequest1 request)
    {
        return base.Channel.getRecurringJobExecutionHistory(request);
    }
    
    public GetRecurringJobExecutionHistoryResponse getRecurringJobExecutionHistory(GetRecurringJobExecutionHistoryRequest getRecurringJobExecutionHistoryRequest)
    {
        getRecurringJobExecutionHistoryRequest1 inValue = new getRecurringJobExecutionHistoryRequest1();
        inValue.getRecurringJobExecutionHistoryRequest = getRecurringJobExecutionHistoryRequest;
        getRecurringJobExecutionHistoryResponse1 retVal = ((BulkDataExchangeServicePort)(this)).getRecurringJobExecutionHistory(inValue);
        return retVal.getRecurringJobExecutionHistoryResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    activateRecurringJobResponse1 BulkDataExchangeServicePort.activateRecurringJob(activateRecurringJobRequest1 request)
    {
        return base.Channel.activateRecurringJob(request);
    }
    
    public ActivateRecurringJobResponse activateRecurringJob(ActivateRecurringJobRequest activateRecurringJobRequest)
    {
        activateRecurringJobRequest1 inValue = new activateRecurringJobRequest1();
        inValue.activateRecurringJobRequest = activateRecurringJobRequest;
        activateRecurringJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).activateRecurringJob(inValue);
        return retVal.activateRecurringJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    suspendRecurringJobResponse1 BulkDataExchangeServicePort.suspendRecurringJob(suspendRecurringJobRequest1 request)
    {
        return base.Channel.suspendRecurringJob(request);
    }
    
    public SuspendRecurringJobResponse suspendRecurringJob(SuspendRecurringJobRequest suspendRecurringJobRequest)
    {
        suspendRecurringJobRequest1 inValue = new suspendRecurringJobRequest1();
        inValue.suspendRecurringJobRequest = suspendRecurringJobRequest;
        suspendRecurringJobResponse1 retVal = ((BulkDataExchangeServicePort)(this)).suspendRecurringJob(inValue);
        return retVal.suspendRecurringJobResponse;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    abortRecurringJobExecutionResponse1 BulkDataExchangeServicePort.abortRecurringJobExecution(abortRecurringJobExecutionRequest1 request)
    {
        return base.Channel.abortRecurringJobExecution(request);
    }
    
    public AbortRecurringJobExecutionResponse abortRecurringJobExecution(AbortRecurringJobExecutionRequest abortRecurringJobExecutionRequest)
    {
        abortRecurringJobExecutionRequest1 inValue = new abortRecurringJobExecutionRequest1();
        inValue.abortRecurringJobExecutionRequest = abortRecurringJobExecutionRequest;
        abortRecurringJobExecutionResponse1 retVal = ((BulkDataExchangeServicePort)(this)).abortRecurringJobExecution(inValue);
        return retVal.abortRecurringJobExecutionResponse;
    }
}
